export * from './PaginationComp/Pagination/Pagination'
export * from './PaginationComp/PaginationButton/PaginationButton'
export * from './Header/Header'
export * from './Layout/Layout'
export * from './MoviesPages/Movies/Movies'
export * from './MoviesPages/Movie/Movie'
export * from './GenrePage/Genre/Genre'
export * from './GenrePage/Genres/Genres'
